"""Name the clang archive that runs on the machine driving the build.

A repository rule for one boolean, which looks like a lot of machinery until you try
the two shorter ways of getting it.

Bazel has no config setting for the execution platform. It has one for the target,
which is a different question, and it has host_cpu, which is the right question and
prints a deprecation warning on every single invocation telling you to use platform
constraints instead. Platform constraints answer the target question. So the shorter
ways are one that is wrong and one that is noisy.

This matters in exactly one place. A few selects in the cc toolchain are keyed on the
target platform and mean the execution platform, and that was harmless for as long as
the two agreed. A Windows target can now be reached either by cross compiling from
Linux x86_64 or by building on Windows, so the target no longer says which clang runs,
and something has to ask the machine. tools/BUILD.bazel is where the answer is used.

Asking the machine is also the honest framing. This is not a build configuration
anybody would want to override, it is a fact about where bazel is running, and a
repository rule is the one place in Bazel that is allowed to look.
"""

def _impl(rctx):
    windows = rctx.os.name.startswith("windows")
    rctx.file("BUILD.bazel", "")
    rctx.file(
        "host_clang.bzl",
        "# Generated by host_clang_repository.bzl, do not edit.\n" +
        "HOST_IS_WINDOWS = {}\n".format(windows),
    )

host_clang_repository = repository_rule(
    implementation = _impl,
    doc = "Writes HOST_IS_WINDOWS for the machine bazel is running on.",
)
