"""Find the Python interpreter that will run the cc toolchain drivers.

Only a Windows host needs this, and it exists because of what Windows will and will
not start. The three drivers in tools/ are Python scripts, and a Windows host cannot
spawn one: there is no shebang, and CreateProcess refuses a .py whatever the file
association says, so the action fails to launch with error 193 before anything has
been compiled. The way round it is a small .bat next to each script that names an
interpreter, and to write that .bat somebody has to know where the interpreter is.

It cannot be found at action time. Upstream sets --incompatible_strict_action_env, so
an action gets a fixed PATH rather than yours, and on Windows that fixed PATH is
system32, windows, wbem and powershell and nothing else. Python is not installed into
any of them by any installer. Even the py launcher, which an all users install does
put in C:\\Windows, is in the user profile for a per user install, which is the
default the python.org installer offers. So the path has to be resolved once, here,
where a repository rule is allowed to look at the machine, and then written down.

The interpreter is the system one on purpose, and not a Bazel provided one. A toolchain
tool is an input to every compile action in the tree, so a hermetic interpreter here
would put a Python runtime in the input set of every C++ compile in the build.

Set MOJO_HOST_PYTHON to override the search. Everything is resolved to an absolute
path, because the .bat this feeds runs with a PATH that will not find it again.
"""

_ENV_VAR = "MOJO_HOST_PYTHON"

# Tried in order. python3 first on a Unix host because that is the name that means
# version three there. Last on Windows, where python3.exe is usually the App Execution
# Alias in WindowsApps, which is not an interpreter at all: it is a stub that opens the
# Microsoft Store. Every candidate is run before it is believed, which is what catches
# that one, so the order is about which answer is reached first and not about safety.
_WINDOWS_CANDIDATES = ["python", "py", "python3"]

_UNIX_CANDIDATES = ["python3", "python"]

# Asks the candidate what it is. A real interpreter prints its major version and exits
# zero. The Store stub prints nothing useful and does not.
_PROBE = ["-c", "import sys; print(sys.version_info[0])"]

def _works(rctx, path):
    result = rctx.execute([path] + _PROBE)
    return result.return_code == 0 and result.stdout.strip() == "3"

def _impl(rctx):
    windows = rctx.os.name.startswith("windows")

    configured = rctx.getenv(_ENV_VAR, "")
    found = ""
    if configured:
        path = rctx.path(configured)
        if not path.exists:
            fail("{}={} does not exist".format(_ENV_VAR, configured))
        if not _works(rctx, path):
            fail("{}={} is not a python 3 interpreter".format(_ENV_VAR, configured))
        found = str(path)
    else:
        candidates = _WINDOWS_CANDIDATES if windows else _UNIX_CANDIDATES
        for name in candidates:
            path = rctx.which(name)
            if path and _works(rctx, path):
                found = str(path)
                break

    # Not a failure off Windows, where nothing reads this, and not a failure on Windows
    # either. Analysis of a Windows configured build should work on a machine that has
    # no interpreter to offer, the same way it works with no sysroot, and it is the
    # compile action that has no honest way to continue. Failing here would take the
    # whole build down at loading time on a machine that was only ever going to query
    # it. windows_sysroot_repository.bzl makes the same choice for the same reason.
    rctx.file("BUILD.bazel", "")
    rctx.file(
        "host_python.bzl",
        "# Generated by host_python_repository.bzl, do not edit.\n" +
        'HOST_PYTHON = "{}"\n'.format(found.replace("\\", "\\\\")),
    )

host_python_repository = repository_rule(
    implementation = _impl,
    environ = [_ENV_VAR],
    configure = True,
    doc = "Writes HOST_PYTHON, the absolute path of a python3 on this machine.",
)
